/**
 * Mock data for Demo Mode.
 *
 * Used by the mock API interceptor when `localStorage.getItem('demoMode')` is set.
 * Data is intentionally small but realistic enough to exercise every dashboard
 * section without a backend.
 */
import type {
  Property,
  RentalRequest,
  SupportTicket,
  AdminStats,
  ModerationStats,
  Announcement,
  Favorite,
  User,
} from './api';

// ─── Users ────────────────────────────────────────────────────────────────

export const demoUsers: User[] = [
  {
    id: 1,
    name: 'Admin Demo',
    email: 'admin@demo.com',
    phonePrefix: '+57',
    phone: '3001111111',
    cedulaType: 'CC',
    cedula: '1000000001',
    role: 'admin',
    isVerified: true,
    accountStatus: 'active',
    status: 'active',
    authProvider: 'local',
    hasPassword: true,
    tutorialCompleted: true,
    verificationLevel: 2,
    avgRatingAsOwner: 4.8,
    reviewCountAsOwner: 12,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    name: 'Operador Demo',
    email: 'operator@demo.com',
    phonePrefix: '+57',
    phone: '3002222222',
    cedulaType: 'CC',
    cedula: '1000000002',
    role: 'operator',
    isVerified: true,
    accountStatus: 'active',
    status: 'active',
    authProvider: 'local',
    hasPassword: true,
    tutorialCompleted: true,
    verificationLevel: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    name: 'Propietario Demo',
    email: 'owner@demo.com',
    phonePrefix: '+57',
    phone: '3003333333',
    cedulaType: 'CC',
    cedula: '1000000003',
    role: 'propietario',
    isVerified: true,
    accountStatus: 'active',
    status: 'active',
    authProvider: 'local',
    hasPassword: true,
    tutorialCompleted: true,
    verificationLevel: 2,
    avgRatingAsOwner: 4.6,
    reviewCountAsOwner: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 4,
    name: 'Cliente Demo',
    email: 'cliente@demo.com',
    phonePrefix: '+57',
    phone: '3004444444',
    cedulaType: 'CC',
    cedula: '1000000004',
    role: 'cliente',
    isVerified: true,
    accountStatus: 'active',
    status: 'active',
    authProvider: 'local',
    hasPassword: true,
    tutorialCompleted: true,
    verificationLevel: 2,
    avgRatingAsTenant: 4.9,
    reviewCountAsTenant: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 5,
    name: 'Estudiante Demo',
    email: 'estudiante@demo.com',
    phonePrefix: '+57',
    phone: '3005555555',
    cedulaType: 'CC',
    cedula: '1000000005',
    role: 'estudiante',
    isVerified: true,
    accountStatus: 'active',
    status: 'active',
    authProvider: 'local',
    hasPassword: true,
    tutorialCompleted: true,
    verificationLevel: 2,
    avgRatingAsTenant: 4.7,
    reviewCountAsTenant: 3,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoUserByRole: Record<User['role'], User> = {
  admin: demoUsers[0],
  operator: demoUsers[1],
  propietario: demoUsers[2],
  cliente: demoUsers[3],
  estudiante: demoUsers[4],
};

// ─── Properties ───────────────────────────────────────────────────────────

const now = new Date().toISOString();

export const demoProperties: Property[] = [
  {
    id: 1,
    title: 'Apartamento moderno cerca de la universidad',
    description: 'Apartamento luminoso con todos los servicios, ideal para estudiantes.',
    price: 1200000,
    priceType: 'monthly',
    bedrooms: 2,
    bathrooms: 1,
    area: 65,
    type: 'Apartamento',
    furnished: true,
    listingType: 'Alquiler',
    location: 'Bogotá, Chapinero',
    address: 'Calle 72 # 11-25, Apto 302',
    city: 'Bogotá',
    neighborhood: 'Chapinero',
    lat: 4.6271,
    lng: -74.0641,
    features: ['WiFi', 'Aire acondicionado', 'Seguridad 24h', 'Gimnasio'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    mainImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    views: 342,
    isFeatured: true,
    status: 'approved',
    authorId: 3,
    author: demoUsers[2],
    avgRating: 4.5,
    reviewCount: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    title: 'Habitación en residencia estudiantil',
    description: 'Residencia con servicios incluidos, ambiente joven y seguro.',
    price: 450000,
    priceType: 'monthly',
    bedrooms: 1,
    bathrooms: 1,
    roomsWithBathroom: 1,
    area: 20,
    type: 'Residencia',
    furnished: true,
    listingType: 'Alquiler',
    location: 'Bogotá, Teusaquillo',
    address: 'Carrera 7 # 40-30',
    city: 'Bogotá',
    neighborhood: 'Teusaquillo',
    availableRooms: 3,
    occupiedRooms: 5,
    lat: 4.6421,
    lng: -74.0682,
    features: ['WiFi', 'Lavandería', 'Cocina compartida', 'Zona de estudio'],
    images: ['https://images.unsplash.com/photo-1555854877-bab0e4703c25?w=800'],
    mainImage: 'https://images.unsplash.com/photo-1555854877-bab0e4703c25?w=800',
    views: 189,
    isFeatured: false,
    status: 'approved',
    authorId: 3,
    author: demoUsers[2],
    avgRating: 4.2,
    reviewCount: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    title: 'Casa familiar con jardín',
    description: 'Amplia casa en zona residencial, perfecta para familias.',
    price: 3500000,
    priceType: 'monthly',
    bedrooms: 4,
    bathrooms: 3,
    area: 180,
    type: 'Casa',
    furnished: false,
    listingType: 'Alquiler',
    location: 'Bogotá, Suba',
    address: 'Calle 130 # 92-15',
    city: 'Bogotá',
    neighborhood: 'Suba',
    lat: 4.7511,
    lng: -74.0942,
    features: ['Jardín', 'Garaje', 'Patio', 'Seguridad 24h'],
    images: ['https://images.unsplash.com/photo-1568605114967-8130f81a6e54?w=800'],
    mainImage: 'https://images.unsplash.com/photo-1568605114967-8130f81a6e54?w=800',
    views: 521,
    isFeatured: true,
    status: 'approved',
    authorId: 3,
    author: demoUsers[2],
    avgRating: 4.8,
    reviewCount: 15,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 4,
    title: 'Estudio amoblado en el centro',
    description: 'Pequeño estudio ideal para una persona, cerca a transporte.',
    price: 800000,
    priceType: 'monthly',
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    type: 'Estudio',
    furnished: true,
    listingType: 'Alquiler',
    location: 'Bogotá, La Candelaria',
    address: 'Carrera 3 # 12-40',
    city: 'Bogotá',
    neighborhood: 'La Candelaria',
    lat: 4.5981,
    lng: -74.0705,
    features: ['WiFi', 'Aire acondicionado'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    mainImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    views: 98,
    isFeatured: false,
    status: 'pending',
    authorId: 3,
    author: demoUsers[2],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Rental Requests ──────────────────────────────────────────────────────

export const demoRentalRequests: RentalRequest[] = [
  {
    id: 1,
    tenantId: 4,
    tenant: demoUsers[3],
    propertyId: 1,
    property: demoProperties[0],
    ownerId: 3,
    owner: demoUsers[2],
    status: 'pending',
    message: 'Hola, estoy interesada en el apartamento. ¿Podríamos coordinar una visita?',
    moveInDate: '2026-08-01',
    leaseDuration: 12,
    createdAt: now,
  },
  {
    id: 2,
    tenantId: 5,
    tenant: demoUsers[4],
    propertyId: 2,
    property: demoProperties[1],
    ownerId: 3,
    owner: demoUsers[2],
    status: 'accepted',
    message: 'Me gustaría reservar la habitación para el próximo semestre.',
    moveInDate: '2026-08-15',
    leaseDuration: 6,
    respondedAt: now,
    createdAt: now,
  },
  {
    id: 3,
    tenantId: 4,
    tenant: demoUsers[3],
    propertyId: 3,
    property: demoProperties[2],
    ownerId: 3,
    owner: demoUsers[2],
    status: 'payment_submitted',
    message: 'Listo para proceder con el pago.',
    moveInDate: '2026-09-01',
    leaseDuration: 24,
    respondedAt: now,
    createdAt: now,
  },
];

// ─── Support Tickets ──────────────────────────────────────────────────────

export const demoTickets: SupportTicket[] = [
  {
    id: 1,
    userId: 4,
    user: demoUsers[3],
    subject: 'No puedo subir fotos de mi cédula',
    message: 'El formulario de KYC no me deja adjuntar archivos.',
    status: 'open',
    priority: 'high',
    moderatorId: null,
    moderatorReply: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    userId: 3,
    user: demoUsers[2],
    subject: 'Consulta sobre comisiones',
    message: '¿Cuál es el porcentaje de comisión por alquiler?',
    status: 'in_progress',
    priority: 'low',
    moderatorId: 2,
    moderator: demoUsers[1],
    moderatorReply: null,
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Favorites ────────────────────────────────────────────────────────────

export const demoFavorites: Favorite[] = [
  {
    id: 1,
    userId: 4,
    propertyId: 1,
    property: demoProperties[0],
    createdAt: now,
  },
  {
    id: 2,
    userId: 4,
    propertyId: 3,
    property: demoProperties[2],
    createdAt: now,
  },
];

// ─── Announcements ────────────────────────────────────────────────────────

export const demoAnnouncements: Announcement[] = [
  {
    id: 1,
    title: 'Bienvenido a Ohana',
    content: 'Explora todas las funciones de la plataforma en este modo demo.',
    targetAudience: 'all',
    status: 'active',
    createdById: 1,
    createdBy: { id: 1, name: 'Admin Demo', email: 'admin@demo.com' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    title: 'Nuevas zonas disponibles',
    content: 'Hemos expandido cobertura a nuevas zonas de la ciudad.',
    targetAudience: 'clients',
    status: 'draft',
    createdById: 1,
    createdBy: { id: 1, name: 'Admin Demo', email: 'admin@demo.com' },
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Stats ────────────────────────────────────────────────────────────────

export const demoAdminStats: AdminStats = {
  totals: {
    users: 1248,
    properties: 342,
    requests: 87,
    pendingTickets: 5,
    operators: 8,
    pendingProperties: 12,
    approvedProperties: 318,
    activeAnnouncements: 3,
  },
  growth: {
    usersThisMonth: 124,
    usersLastMonth: 110,
    userGrowthPercent: 12.7,
    propertiesThisMonth: 28,
  },
  recentUsers: demoUsers,
};

export const demoModerationStats: ModerationStats = {
  today: {
    propertiesModerated: 14,
    propertiesApproved: 11,
    propertiesRejected: 3,
    usersVerified: 7,
    resolvedTickets: 4,
    totalActions: 26,
  },
  pending: {
    tasks: 3,
    properties: 12,
    verifications: 5,
    tickets: 5,
    reports: 2,
    total: 27,
  },
};

// ─── Helper to simulate network latency ───────────────────────────────────

export function mockDelay<T>(value: T, ms = 200): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}
